### ISSUE TITLE
Missing OSVR.ClientKit.dll.mdb

### ISSUE THREAD

**Issue by Such1337Hax0r** [OSVR/OSVR-Unity#113]
After updating to the latest version unity has the following error:

System.IO.FileNotFoundException: Could not find file "Assets/Plugins/OSVR.ClientKit.dll.mdb".

**Comment by DuFF14** [comment]
Probably due to the update. Which version did you update from? Is it blocking you or does the plugin still work? Deleting the Plugins and OSVRUnity folders and importing the plugin again should make it go away.

**Comment by Such1337Hax0r** [comment]
I tried deleting and reinstalling however it didn't work, if by blocking me you mean not allowing me to run/compile yes it is. I forgot the version I updated from

**Comment by Such1337Hax0r** [comment]
Fixed by renaming OSVR.ClientKit.dll.pdb to OSVR.ClientKit.dll.mdb not sure if that was a typo or intentional
