### ISSUE TITLE
Investigate "LostNative" for alternate handling of p/invoke

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unity#13]
Might solve some of our "help where's my native DLL/SO" issues. https://www.nuget.org/packages/Lost.Native/

**Comment by JeroMiya** [comment]
I moved this issue to: https://github.com/OSVR/Managed-OSVR/issues/8

Recommend closing this one.

**Comment by rpavlik** [comment]
Thanks!
