### ISSUE TITLE
Update repo to Unity 5

### ISSUE THREAD

**Issue by DuFF14** [OSVR/OSVR-Unity#132]
No good reasons to continue supporting Unity 4. Could only cause issues if committing files from a Unity 5 project.

**Comment by rpavlik** [comment]
Do we need to update the CI then? it's building the unitypackage with unity 4.6.1 IIRC

**Comment by DuFF14** [comment]
Yes, this might be required for running the script which changes the default plugin platform.

**Comment by DuFF14** [comment]
Unity 5.2 might be a good minimum version? I think that's what I used to submit the latest asset store update.

**Comment by rpavlik** [comment]
Then send me an email with a link to which version (exactly) of Unity you want on the CI server, and then I'll put it on there and you can adjust the CI build accordingly.
