### ISSUE TITLE
Not detecting osvr_server with osvr_server_config.HDK13ExtendedLandscape.sample.json

### ISSUE THREAD

**Issue by Such1337Hax0r** [OSVR/OSVR-Unity#133]
I am on mac osx 10.10.5 with the HDK 1.3 and unity 5.3.2f1 personal and the latest homebrew version of osvr server as the title says I am using osvr_server_config.HDK13ExtendedLandscape.sample.json and the unity plugin won't detect the server

**Comment by DuFF14** [comment]
Is tracker view working? http://osvr.github.io/using/

**Comment by Such1337Hax0r** [comment]
'''[OSVR] Interface initialized for /me/hands/left
[OSVR] Could not resolve source for /me/hands/left
[OSVR] Interface initialized for /me/hands/right
[OSVR] Could not resolve source for /me/hands/right
[OSVR] Interface initialized for /me/head
[OSVR] Could not resolve source for /me/head
vrpn_Endpoint::send_pending_reports(): No TCP connection
vrpn_Connection_IP::send_pending_reports:  Closing failed endpoint.
vrpn_Connection::~vrpn_Connection: Connection was deleted while 5 references still remain.
'''

**Comment by Such1337Hax0r** [comment]
Tracker View:
[OSVR] Interface initialized for /me/hands/left
[OSVR] Could not resolve source for /me/hands/left
[OSVR] Interface initialized for /me/hands/right
[OSVR] Could not resolve source for /me/hands/right
[OSVR] Interface initialized for /me/head
[OSVR] Could not resolve source for /me/head

**Comment by Such1337Hax0r** [comment]
Also when I started the server this happened:
[OSVR] Interface initialized for /com_osvr_Multiserver/OSVRHackerDevKitPrediction0/semantic/hmd
[OSVR] Could not resolve source for /com_osvr_Multiserver/OSVRHackerDevKitPrediction0/semantic/hmd
[OSVR] Interface initialized for /com_osvr_VideoBasedHMDTracker/TrackedCamera0_0/semantic/hmd/front
[OSVR] Could not resolve source for /com_osvr_VideoBasedHMDTracker/TrackedCamera0_0/semantic/hmd/front

**Comment by DuFF14** [comment]
The server isn't finding the HDK. I would make sure your drivers are up to date (https://github.com/OSVR/OSVR-Docs/blob/master/Getting-Started/HDK/HDK-Unboxing-and-Getting-Started.md) and seek help through a support ticket or gitter. This is a server connection issue on OSX, so I'm closing the issue here.

**Comment by Such1337Hax0r** [comment]
It still says: "[OSVR] Added device: com_osvr_Multiserver/OSVRHackerDevKit0"

**Comment by Such1337Hax0r** [comment]
The drivers are windows only

**Comment by DuFF14** [comment]
Can you see the HMD moving around in tracker view?

**Comment by Such1337Hax0r** [comment]
I am unable to see the HMD moving around in the tracker view

**Comment by DuFF14** [comment]
Ok, closing this again as it is a server issue, but you can open up a new ticket to pull the Mac binaries into the Unity plugin when you get there. Work on getting Tracker View to show the HMD first.
