### ISSUE TITLE
Description text for Asset Store page.

### ISSUE THREAD

**Issue by chase-cobb** [OSVR/OSVR-Unity#150]
This was mentioned in #146 but there is a discrepancy in the plugin description text on the Unity Asset store.

https://www.assetstore.unity3d.com/en/#!/content/36905

Compatability requirements at the top:
> Requires Unity 5.2.2 or higher.

Then below that:
> OSVR Plugin for Unity is compatible with Unity 4 and 5 Free and Pro versions (image distortion is disabled in Unity 4 Free version).

**Comment by DuFF14** [comment]
It still works with Unity 4, but the Unity Rendering Plugin requires at least Unity 5.2. I'll change the description. I'd be surprised if there are any Unity 4 users, as Unity support has been discontinued.

**Comment by chase-cobb** [comment]
There may be Unity 4 legacy games that may want to do a quick VR port.

**Comment by DuFF14** [comment]
Rather than change the description, I uploaded two versions this time around, so Unity 4 users can still download the plugin (once its approved). If we decide to drop the Unity 4 version, I'll update the text.
