### ISSUE TITLE
Unity 5.3.3p can't connect to osvr server

### ISSUE THREAD

**Issue by MarcinRNowak** [OSVR/OSVR-Unity#155]
Hi,

I am trying to run Unity samples, but no luck. I have:
- Unity 5.3.3p
- Geforce 980m with 362.00 drivers
- newset OSVR SDK
- newst unity package
- osvr server running (from unity package)

In unity console I can see error message (can't connect to osvr server) and then whole Unity editor hangs. It happens when I press "play" button on any sample scene.

I will be very happy for any suggestions.

Best Regards,
Marcin

**Comment by DuFF14** [comment]
Hi Marcin,
Does Tracker View work for you?
If so, can you see if the changes in my last comment here fixes the issue for you? https://github.com/OSVR/OSVR-Unity/issues/127

**Comment by MarcinRNowak** [comment]
Hi DuFF14,

Tracker View does work. I have tried your fix, but it doesn't help unfortunately. I have tried uninstalling OSCR Runtime and let Razer Synapse install whatever version it does. 
After I did it, I don't get any picture when I run OSVR demo scene, or from Unity. HMD's screen is black, hoever Unity doesn't hang. There is the same connection error in Unity console, but then it tries to reconnect and it manages to do so. Tracking works, but no picture.

Honestly I have no clue what to do. I have updated HMD's firmware, but it didn't help.

Best Regard,
Marcin

**Comment by MarcinRNowak** [comment]
I have some small progress: I managed to run it by:
1. disconnecting HMD's USB cable
2. Running sample i Unity
3. Reconnecting USB after connection to server is established

I can see white vertical line between left are right eye. Tracking quality is quite bad, but it works otherwise.

**Comment by DuFF14** [comment]
Hmm, that's odd that you'd have to connect after starting the server. Perhaps there is an issue with the cable connection to the belt box. Sometimes USB will go out on me if the belt box is jostled, required a power cycle/cable reseat.

I'm not sure what the Razer Synapse install is doing. I use the OSVR runtime. I hope there aren't many differences between them.

The white line is a known issue that only shows up in the Unity editor.

As for tracking quality, are you using positional tracking or orientation only? Do you see latency? Maybe you could try the config file below (make sure to rename .txt to .json), which may work better than the default after this pull request: https://github.com/OSVR/OSVR-Core/pull/399 Not sure if you tested before or after this PR, it looks like it was merged on the same day that you filed this issue.

[HDK1.3_predict.json.txt](https://github.com/OSVR/OSVR-Unity/files/234867/HDK1.3_predict.json.txt)

**Comment by MarcinRNowak** [comment]
Hi,

many thanks it helped a lot! I was using positional tracking. I uninstalled again OSVR SDK and downloaded just the newest Runtime. I reconnected all the cables and now everything seems to be working fine :) Tracking is still a bit slow comparing to say Gear VR, but it is much better then it used to be. 

Many thanks and best regards,
Marcin

**Comment by DuFF14** [comment]
Great. GearVR uses asynchronous timewarp, which we'll soon have working in Unity. Hopefully that will improve perceived latency.
http://vrguy.blogspot.com/2016/04/time-warp-explained.html
