### ISSUE TITLE
Can't build a project when targeting Android

### ISSUE THREAD

**Issue by demonixis** [OSVR/OSVR-Unity#177]
Hi,

I have a project which runs fine on a standalone build but when I try to build for Android, I've these errors

![image](https://cloud.githubusercontent.com/assets/1017126/17035735/4a430cf0-4f89-11e6-88a1-54ff214d33c3.png)

Edit : I know why

![image](https://cloud.githubusercontent.com/assets/1017126/17035771/80ac2a24-4f89-11e6-949f-9a10a31fa255.png)

Dlls have to be checked only for the Editor **and** the standalone build. If you want I can prepare a PR with this fix.

**Comment by DuFF14** [comment]
See https://github.com/OSVR/OSVR-Unity/issues/146
This requires a script to run at unitypackage build time since the DLLs are copied from Managed-OSVR at that time. Would be great to have this issued resolved if you are able to make a PR.
