### ISSUE TITLE
Side By Side not toggling

### ISSUE THREAD

**Issue by SpydyrByte** [OSVR/OSVR-Unity#186]
I updated to the new OSVR software as of 8/18/2016. I like how it is simple now but I have encountered a bug. I cannot seem to toggle side by side, it is stuck in that mode. Anything I try does not work,

**Comment by DuFF14** [comment]
You can toggle SBS mode with [OSVR Control](http://sensics.com/software/OSVRControl-SW/publish.htm) or the OSVR CPI which comes with [this installer](http://www.osvr.org/getting-started.html).
