### ISSUE TITLE
Confusing image on 'Getting started' tutorial

### ISSUE THREAD

**Issue by Moisi** [OSVR/OSVR-Unity#189]
The Image in the Getting started tutorial might be confusing for a new developer wishing to see on his pc the exact picture on the tutorial.

referencing this iamge: [https://raw.githubusercontent.com/OSVR/OSVR-Unity/master/images/osvr_unity_editor.png]

**Comment by DuFF14** [comment]
Fixed in https://github.com/OSVR/OSVR-Unity/pull/191, thanks.
