### ISSUE TITLE
OSVR.Unity.InterfaceCallbacks.PoseCallback should take one value argument

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/OSVR-Unity#20]
Currently PoseCallback takes a position and a rotation:

```C#
public delegate void PoseCallback(string source, Vector3 position, Quaternion rotation);
```

In order to help support more generic callback code, a single 'value' type should be used for each report. In this case, since we have multiple values, a wrapper struct should be constructed:

```C#
public struct PoseReport
{
    Vector3 Position { get; set; }
    Quaternion Rotation { get; set; }
}

public delegate void PoseCallback(string source, PoseReport pose);
```

This allows, hypothetically, a common generic interface callback:
```C#
public delegate void InterfaceCallback<T>(string source, T value) where T : struct;
```

**Comment by DuFF14** [comment]
@JeroMiya ok to close this issue now that InterfaceCallback is in Managed-OSVR?

**Comment by JeroMiya** [comment]
Yes, I think so.
