### ISSUE TITLE
Read input during Update() rather than FixedUpdate()

### ISSUE THREAD

**Issue by jfrank-razer** [OSVR/OSVR-Unity#202]
Reading input (e.g. keyboard state) should be done during Update(), not FixedUpdate().

For example, [this](https://github.com/OSVR/OSVR-Unity/blob/master/OSVR-Unity/Assets/OSVRUnity/Sample/Scripts/SetRoomRotationUsingHead.cs#L44) is unreliable but would work fine when if moved to Update().

**Comment by DuFF14** [comment]
Thanks, fixed in https://github.com/OSVR/OSVR-Unity/pull/203
