### ISSUE TITLE
Terrain flickers in VR build (but not in editor)

### ISSUE THREAD

**Issue by amiga** [OSVR/OSVR-Unity#210]
I finally got something building, it ALL seems to be down to that i was using 1920x1080, I noticed the palace demo which works uses a lower res, now I can build my demo. But the terrain flickers, flickering goes away when terrain is turned off, any thoughts? Going to try some new terrains tomorrow. The demo works fine with no flicker in the editor!

**Comment by DuFF14** [comment]
I think we just resolved this on gitter.

**Comment by jfrank-razer** [comment]
@DuFF14 Does this also resolve https://github.com/OSVR/OSVR-Unity-Rendering/issues/31?

**Comment by DuFF14** [comment]
@jfrank-razer this issue was not related to OSVR, it sounded like a script causing a mobile shader to turn on and off.
