### ISSUE TITLE
RenderManager config found but RenderManager is not supported

### ISSUE THREAD

**Issue by atmuc** [OSVR/OSVR-Unity#214]
i use following assets;

OSVR-SDK-v0.6-1935-ga2cba4b6-build356-win-32bit.msi
OSVR-Unity-v0.6.16.3-with-core-v0.6-1935-ga2cba4b6-build615.7z
OSVR-HDK-Combined-Driver-Installer-1.2.8.exe
Unity 5.6.0f1

unity osvr settings;
c:\Program Files (x86)\OSVR\Runtime\bin\
"C:\Program Files (x86)\OSVR\Runtime\bin\osvr_server_config.json"

i open scene OSVRDemo and click play on unity i get following error. i tried to change nvidia driver versions. i always get following error. On OSVR Central i can run "Solid Color" and "D3D Present Example 3D". i can see vision on my HDK2. when i play on unity HDK2 is blank.

[OSVR-Unity] RenderManager config found but RenderManager is not supported.
UnityEngine.Debug:LogError(Object)
OSVR.Unity.DisplayController:SetupRenderManager() (at Assets/OSVRUnity/src/DisplayController.cs:133)
OSVR.Unity.DisplayController:SetupDisplay() (at Assets/OSVRUnity/src/DisplayController.cs:175)
OSVR.Unity.DisplayController:Update() (at Assets/OSVRUnity/src/DisplayController.cs:316)

**Comment by DuFF14** [comment]
Can you debug where it's setting supported = false in this function? 
https://github.com/OSVR/OSVR-Unity/blob/master/OSVR-Unity/Assets/OSVRUnity/src/OsvrRenderManager.cs#L333

**Comment by atmuc** [comment]
Here;

#if UNITY_ANDROID
                Debug.Log("[OSVR-Unity] RenderManager not yet supported on Android.");
                support = false;
#endif

it is strange. my build target is windows. i commented those lines and it works now. i spent hours for it :-)

**Comment by DuFF14** [comment]
Weird. Could it be a bug in Unity 5.6 beta? (do you get the same error on older versions of Unity?)
