### ISSUE TITLE
The Standard shader doesn't render when the HDK2 is connected

### ISSUE THREAD

**Issue by demonixis** [OSVR/OSVR-Unity#228]
Hi,

I have a serious issue with OSVR (works well on Oculus, Flat mode, etc...), I suspect that it's related to the UnityRenderingPlugin but I'm not sure. I use the latest HDK firmware (2.0 which is work really well), the latest OSVR Oneclick installer (0.8) and of course the latest Unity SDK from this repository (Nice job for the OsvrMirror script ;)). My PC uses an AMD RX 480 8Gb with the latest drivers on Windows 10 Creator Update.

Now let's talk about the issue, please take a look at those sreenshots

![gunspinning vr_2017-04-25_20-43-49](https://cloud.githubusercontent.com/assets/1017126/25419425/f4dbf574-2a52-11e7-86fc-0539e6f47d96.png)

![gunspinning vr_2017-04-25_20-32-46](https://cloud.githubusercontent.com/assets/1017126/25419426/f4dfcc08-2a52-11e7-8e66-ec4590b176a4.png)

In my scenes, I use the standard shader, somes lights and of course lightmapping. All static objects are lightmapped (the ones who are white, are not lightmapped). As you can see, all non lightmapped object are white! If I change the shader, by an unlit (without lightmap) by example, it's fine, as you can see on the screenshot below

![gunspinning vr_2017-04-25_20-44-05](https://cloud.githubusercontent.com/assets/1017126/25419555/9a42c042-2a53-11e7-94c4-1d02b1745c1f.png)

The ground is still white because it's a terrain and I don't have changed its material.

Any idea about this issue?

**Comment by DuFF14** [comment]
The fastest way to determine if this is an OSVR-Unity issue is to revert to the previous working version of OSVR-Unity and see if the issue goes away.

I see you also commented in a [reddit thread](https://www.reddit.com/r/OSVR/comments/6789t9/windows_10_creators_update/) that the Windows Creator update was working for you, but have you only noticed the issue after the Windows 10 update?

The title suggest this is an HDK2 issue. Do you not see the same problem with HDK 1.4?

Which version of Unity are you using, and have you updated that recently as well?

**Comment by demonixis** [comment]
I can try an older version yes.

The Creator update works well for me yes, I just tested the sample and it works perfectly (installer 0.8). With Unity I have this issue.

This is an HDK2 issue, not tested with my other HDKs. I'll try that asap and update this thread.

I use the latest Unity version 5.6.0p2 (but I also have the issue with 5.6.0f3)

**Comment by DuFF14** [comment]
If the lightmaps were baked with an older version of Unity, maybe try clearing and re-baking with the current version.

**Comment by demonixis** [comment]
Well, after a first test I can say that I've this issue with

- An NVIDIA GPU too (980 GTX)
- A HDK 1.4 (firmware 2.0)
- The latest runtime

So it's an issue which doesn't depend of the GPU.

**Comment by demonixis** [comment]
OK I know what is not working, it's the deferred renderer. If I switch to Forward, it works. So for now I'll force the forward renderer for OSVR users. But I recommand you to test this rendering path with the SDK.

**Comment by DuFF14** [comment]
Opened a new issue related to this, https://github.com/OSVR/OSVR-Unity/issues/229
