### ISSUE TITLE
License for SimpleJSON.cs

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unity#25]
When going through files, noticed that SimpleJSON was "vendored-in" but does not appear to have a license header.  This file needs to be a: annotated with the correct license from upstream or b: removed and replaced with an alternative.

An addition to the `NOTICE` file might also be required depending on the license of that file.

**Comment by rpavlik** [comment]
Possible alternative: https://github.com/JamesNK/Newtonsoft.Json

**Comment by JeroMiya** [comment]
Newtonsoft.Json is the de-facto standard json parser/serializer for .net. Even Microsoft uses it. It's MIT licensed.

**Comment by rpavlik** [comment]
Resolved by use of Newtonsoft.Json
