### ISSUE TITLE
Move Managed-OSVR into its own repo

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/OSVR-Unity#3]
I'll be working on an OSVR-MonoGame when this goes fully open source. Please move the Managed-OSVR code into its own repo to facilitate this. Other community contributed ports/integration efforts would benefit as well.

I didn't see any at first glance, but if there is any unity-specific code in OSVR-MonoGame, please #ifdef it or preferably factor the code out into a partial class implementation or configurable helper class, per your choice. It would be helpful for me, not having any unity experience, to add some explanation into what the unity code is doing so I can determine whether it is even applicable to a MonoGame port.

I'll leave it up to you to determine the best way to get Managed-OSVR into OSVR-Unity, and I'll follow suit with OSVR-MonoGame. Perhaps checking in the binaries, or a git submodule, or a build/copy script, or symbolic links, or a pre-release NuGet package when this repo is fully public.

As an aside: I haven't had a lot of time to review the code, but from what I see so far there seems to be a fair amount of code in the Unity plugin that is not Unity specific. Perhaps some of that can be moved into the Managed-OSVR code instead?

**Comment by JeroMiya** [comment]
Some questions from @rpavlik from https://github.com/OSVR/OSVR-Unity/issues/6

Q: Do people usually use a single nuget provider or should we be using myget for example?
A: Registration on NuGet.org is the preferred way. Registration on MyGet et. al. is typically for private nuget repo scenarios - internal development, etc... It's an option if you need some internal builds, but generally speaking open source projects are registered on NuGet.org to take advantage of the ecosystem.

Q: Is there a preferred way to handle providing bins for the two framework versions?
A: Yes. You can create a single NuGet package with bins for multiple framework versions. See here for documentation: https://docs.nuget.org/Create/Enforced-Package-Conventions

Q: How about distributing the native libraries?
A: This appears to be still something NuGet doesn't support natively (http://nuget.codeplex.com/workitem/679) but there seem to be a few workarounds (the powershell script solution doesn't work cross platform though):
https://npe.codeplex.com/discussions/462174
http://stackoverflow.com/questions/7769580/how-should-i-create-or-upload-a-32-bit-and-64-bit-nuget-package

**Comment by rpavlik** [comment]
OK, I split out the repo, though I haven't ported the Unity code in this repo to use it yet. https://github.com/OSVR/Managed-OSVR
