### ISSUE TITLE
Read display parameters from JSON file at runtime

### ISSUE THREAD

**Issue by yboger** [OSVR/OSVR-Unity#32]
Right now, JSON descriptor files need to be brought into prefab. Modify so that JSON file (display parameters such as FOV, overlap) are read at runtime, thus allowing to quickly change between displays.

**Comment by DuFF14** [comment]
Unity build will look for "hmd.json" in the _Data folder. If the file doesn't exist, it will fall back to the JSON descriptor set in the editor. If none is set, it will fall back to reading from /display.
