### ISSUE TITLE
Unity4 to Unity5: dll x64 problem

### ISSUE THREAD

**Issue by LeeSai** [OSVR/OSVR-Unity#34]
hi

I just success running Oculus DK2 with OSVR in Unity4, and when I open that project folder with Unity5, I got this error message:

Failed to load 'Assets/Plugins/x86_64/osvrClientKit.dll' with error '%1 is not a valid Win32 application.
', GetDllDirectory returned ''. If GetDllDirectory returned non empty path, check that you're using SetDirectoryDll correctly.
OSVR.Unity.ClientKit:EnsureStarted() (at Assets/OSVRUnity/src/ClientKit.cs:76)
OSVR.Unity.ClientKit:EnsureStarted() (at Assets/OSVRUnity/src/ClientKit.cs:74)
OSVR.Unity.ClientKit:OnEnable() (at Assets/OSVRUnity/src/ClientKit.cs:99)

The osvrClientKit  file I use from OSVR Code x64. I also try use osvrClientKit from x86 folder, but it shows up another error message:

Failed to load 'Assets/Plugins/x86_64/osvrClientKit.dll', expected 64 bit architecture (IMAGE_FILE_MACHINE_AMD64), but was IMAGE_FILE_MACHINE_I386.
OSVR.Unity.ClientKit:EnsureStarted() (at Assets/OSVRUnity/src/ClientKit.cs:76)
OSVR.Unity.ClientKit:EnsureStarted() (at Assets/OSVRUnity/src/ClientKit.cs:74)
OSVR.Unity.ClientKit:OnEnable() (at Assets/OSVRUnity/src/ClientKit.cs:99)

So.. I guess, I don't have right dll file Unity5 need.
The question is where can I find these dll x64 files?

thx

**Comment by DuFF14** [comment]
Looks like you are using the 64-bit version of the Unity editor. OSVR currently works with the 32-bit version. You can download the 32-bit version of Unity 5 from the link below by selecting it from the "Additional Downloads" drop-down.
https://unity3d.com/get-unity/update

**Comment by LeeSai** [comment]
thx for your reply, i will try it :)

**Comment by rpavlik** [comment]
Unity 64-bit support is tracked here: https://github.com/OSVR/OSVR-Unity/milestones/64-bit%20Unity%20Plugin

**Comment by wahengchang** [comment]
osvr look like doesnt have much information and doc to read, nightmare

**Comment by yboger** [comment]
Lots of information at osvr.github.io
