### ISSUE TITLE
Displays and Plugins folder missing from server included in Unity snapshot

### ISSUE THREAD

**Issue by DuFF14** [OSVR/OSVR-Unity#42]
The osvr_server included in the Unity Snapshot is missing the displays, osvr-plugins-0, and sample-configs folders. If I copy them over from the Core Snapshot, it's still unable to find the plugin (testing with Oculus Rift DK2).

**Comment by rpavlik** [comment]
So I thought this was in the build scripts in the repo, but it looks like it must be directly in the CI configuration where the copying is done.

**Comment by DuFF14** [comment]
Displays folder has been removed. Plugins folder is included in the snapshot. Closing.

**Comment by rpavlik** [comment]
Well, there should be a displays folder in the server that's distributed...

**Comment by DuFF14** [comment]
ah, yea, misread my own post. Anyways, this has been resolved.
