### ISSUE TITLE
ClientKit should use persistent singleton pattern

### ISSUE THREAD

**Issue by DuFF14** [OSVR/OSVR-Unity#45]
ClientKit.cs calls DontDestroyOnLoad() in it's Awake() function. If you load new scenes that also have a ClientKit prefab, then you have multiple ClientKits trying to communicate with the server, which is causing very high latency and throws NullReferenceExceptions in Interface Callbacks.

There should only be one ClientKit in the scene, and the persistent singleton pattern should enforce this: http://unitypatterns.com/singletons/

**Comment by rpavlik** [comment]
Should coordinate with work in https://github.com/OSVR/Managed-OSVR/pull/10

**Comment by rpavlik** [comment]
and actually I've now merged that pull request

**Comment by rpavlik** [comment]
c.f. what Cardboard does: note that by default they don't keep the object around between scenes, which we'd want, but useful example:

The guts of it: https://github.com/googlesamples/cardboard-unity/blob/master/Cardboard/Scripts/Cardboard.cs#L26

The `Awake` method: https://github.com/googlesamples/cardboard-unity/blob/master/Cardboard/Scripts/Cardboard.cs#L323
