### ISSUE TITLE
Move callback wrapper code from Unity plugin up into Managed-OSVR

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unity#5]
There's callback wrapper code (mostly generated, IIRC, using the Lua script) that makes a more idiomatic .NET interface for registering callbacks on interfaces. Any Unity-specific pieces should be factored out and this should go up into Managed-OSVR to be used by other .NET consumers

cc @JeroMiya

**Comment by JeroMiya** [comment]
This can be closed. It will be implemented as part of this issue:
https://github.com/OSVR/Managed-OSVR/issues/7
