### ISSUE TITLE
Reducing allocations/fix memory leak

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unity#51]
We have a report that leaving a Unity game running for about 45 minutes causes an out of memory crash. Core applications have been left running a lot longer than that with no ill effects, so the issue is most likely in Managed-OSVR or OSVR-Unity.

From Radial-G OSVR 0.2.77 (so that might be the Unity build number or the core build number), the version of OSVR-Unity compiled in has this interesting disassembly (from ILSpy):

```
.method private hidebysig 
			instance void OnDestroy () cil managed 
		{
			// Method begins at RVA 0x98f70
			// Code size 40 (0x28)
			.maxstack 8

			IL_0000: ldstr "OnDestroy"
			IL_0005: call void [UnityEngine]UnityEngine.MonoBehaviour::print(object)
			IL_000a: ldarg.0
			IL_000b: call instance class OSVR.Unity.InterfaceCallbacks OSVR.Unity.InterfaceGameObject::get_osvrInterface()
			IL_0010: ldarg.0
			IL_0011: ldftn instance void OSVR.Unity.PoseInterface::callback(string, valuetype [UnityEngine]UnityEngine.Vector3, valuetype [UnityEngine]UnityEngine.Quaternion)
			IL_0017: newobj instance void OSVR.Unity.InterfaceCallbacks/PoseCallback::.ctor(object, native int)
			IL_001c: callvirt instance void OSVR.Unity.InterfaceCallbacks::RemoveCallback(class OSVR.Unity.InterfaceCallbacks/PoseCallback)
			IL_0021: ldarg.0
			IL_0022: call instance void OSVR.Unity.InterfaceGameObject::Stop()
			IL_0027: ret
		} // end of method PoseInterface::OnDestroy
```

So OnDestroy of a pose interface is allocating a pose callback then calling to unregister it. I'm thus a) not sure the underlying code does what I think it does and b) suspecting this probably isn't helping memory pressure, though creating/destroying pose interfaces is probably not common enough to be our leak.

**Comment by rpavlik** [comment]
Resources: Three part article starting here: http://www.gamasutra.com/blogs/WendelinReich/20131109/203841/C_Memory_Management_for_Unity_Developers_part_1_of_3.php

Interesting statement at http://www.gamasutra.com/blogs/WendelinReich/20131109/203841/C_Memory_Management_for_Unity_Developers_part_1_of_3.php#comment222977 , not sure if it's still valid:

> Using Destroy instead of Dispose is also a good strategy to mark objects for deletion and letting Unity decide when to do it as it is has more knowledge about the nature of the application (i.e. a game engine) than the garbage collector itself.

**Comment by rpavlik** [comment]
Looks like `ClientKit.get_instance()` accounts for most of the OSVR-related runtime and also for 24 bytes of GC allocations, I assume per frame - not much compared to other things in the same scene, but of the same order of magnitude. (This was testing the Palace demo in Unity 5.0)

**Comment by JeroMiya** [comment]
Can you cache the ```ClientKit``` instance in a static field instead of injecting it each time the getter is called?

**Comment by rpavlik** [comment]
I'm sure the way I did that singleton is sub-optimal. I think @DuFF14 was working on an alternate one, though I don't know the status of it.

As a clarification, it only accounts for a chunk of time when the OSVR server isn't started, so it's continually trying to load the display descriptor. Once it has the string, that goes away, but yes, still a good thing to improve.

**Comment by JeroMiya** [comment]
![trackercallbackprofiling](https://cloud.githubusercontent.com/assets/320332/8199302/0ab9ffba-1481-11e5-94e5-fb9601d5b657.JPG)

If it helps, I modified the samples in Managed-OSVR to loop endlessly and took snapshots over a period of about 2 minutes and wasn't able to detect any allocations in either managed or native code after the loop got started.

**Comment by DuFF14** [comment]
Not sure about the status here. Could have been resolved by https://github.com/OSVR/OSVR-Unity/pull/52. Haven't been able to reproduce, and I don't think this bug has been reported by others. Will keep this open for now, unless @rpavlik or @JeroMiya are confident this is no longer an issue.

**Comment by rpavlik** [comment]
If you can't reproduce it (maybe leave the boxes demo running overnight?) then close it.
