### ISSUE TITLE
InterfaceAdapter implementations for Unity

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/OSVR-Unity#53]
Implement OSVR.ClientKit.InterfaceAdapter sub-classes for Unity and use them in the Unity specific wrappers in place of InterfaceCallbacks. Make appropriate changes to InterfaceGameObject and InterfaceBase to facilitate this, taking care to remain backward compatible where possible.

Research:
 * Can Unity handle a generic InterfaceGameObject and InterfaceBase implementation? This would be ideal to support typed interface wrappers for scripts, but we can work around it in several ways if not.

Potential breaking changes:
 * InterfaceGameObject or its subclasses would switch from InterfaceCallbacks to an IInterface<T> implementation (either a unity adapter or the original OSVR.ClientKit ones, e.g. ButtonInterface which doesn't need a unity adapter).
 * If InterfaceGameObject and InterfaceBase can't be generic classes, then they may need to be made abstract, with concrete implementations specific to each interface type. This is more type safe, but existing InterfaceBase sub-classes will need to switch to a more specific type.

This is in-progress. The adapter implementations are done. I'm looking into the research item now, and planning the InterfaceGameObject/InterfaceBase refactor.

**Comment by JeroMiya** [comment]
Status update:
I found a way to do this without generics and with mostly minimal breaking changes. I went with creating a new base class InterfaceGameObjectBase, which InterfaceGameObject now derives from. OrientationInterface, PositionInterface, and PoseInterface now derive from InterfaceGameObjectBase instead of InterfaceGameObject. This allows existing users of InterfaceGameObject and InterfaceBase to continue working without breaking changes!

Work done:
 * Created InterfaceAdapter subclasses for Unity conversions.
 * Created InterfaceGameObjectBase, a new base class of OrientationInterface, PoseInterface, PositionInterface, and InterfaceGameObject (exposes InterfaceCallbacks).
 * Using the State APIs in OrientationInterface, PoseInterface, and PositionInterface.

Work left to do:
 * Classes for each interface type aside from InterfaceBase for components to derive from to inject strongly typed interfaces without attributes or GetComponent<T> usage, like InterfaceBase.
 * InterfaceGameObjectBase subclasses for analog and button interfaces, along with respective InterfaceBase-like utility base classes.

**Comment by JeroMiya** [comment]
OK, this is implemented in a branch here:
https://github.com/OSVR/OSVR-Unity/compare/master...JeroMiya:Adapters

Could I get a code review? Thanks.

**Comment by rpavlik** [comment]
Easiest to comment if you start a pull request.  Does this eliminate the code that used to be generated by that Lua file? (Just re-noticed that script the other day when doing OSVR-Unity/Managed-OSVR transitions.)

**Comment by JeroMiya** [comment]
I left InterfaceCallbacks in place for backwards compatibility, so the lua script is still applicable for now. But maybe I should mark those classes as obsolete?

**Comment by rpavlik** [comment]
Well, if you've got a better way, then please do. I don't remember if anything internal relies on them - it might. (Feel free to modify the lua script to add the deprecated thing and re-generate)

**Comment by JeroMiya** [comment]
I just marked the class as obsolete. No need to modify the lua script. Pull request is up now:
https://github.com/OSVR/OSVR-Unity/pull/57/files
