### ISSUE TITLE
Add Android libraries to the build

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unity#63]
There's placeholders, but right now you have to manually put the files in there. We should be scripting this so that it comes in via the CI.

**Comment by stanmanwplan** [comment]
i9
On Jul 10, 2015 11:42 AM, "R3ange Pavlik" <notifications@github.com> wrote:
>
> There's placeholders, but right now you have to manually put the files in
there. We should be scripting this so that it comes in via the CI.

**Comment by DuFF14** [comment]
Fixed by CI changes following https://github.com/OSVR/OSVR-Unity/pull/130
