### ISSUE TITLE
Support for the imaging interface

### ISSUE THREAD

**Issue by zachkinstner** [OSVR/OSVR-Unity#66]
Is there currently a way to access the imaging interface data via Unity?

**Comment by DuFF14** [comment]
No, this has not made it into Unity. This would be implemented in Managed-OSVR: https://github.com/OSVR/Managed-OSVR/issues/20

**Comment by JeroMiya** [comment]
I imagine there would need to also be some code in OSVR-Unity to facilitate displaying the image data in unity efficiently.

**Comment by DuFF14** [comment]
ImagingInterface and sample has been added to Managed-OSVR and OSVR-Unity https://github.com/OSVR/OSVR-Unity/pull/120
