### ISSUE TITLE
EyeTracker2D/3D, Direction, Location2D, and blink interface support

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/OSVR-Unity#68]
This is in progress. See:
https://github.com/OSVR/OSVR-Unity/compare/master...JeroMiya:EyeTrackerInterfaces

Adapters, interface game objects, injection utilities, and prefabs are complete. Just working on a little tracking visualization. I've settled on adding an eye tracker axis in the trackerviewer scene. Eventually it would be nice to have some sample code for "picking" an item in a scene via eye tracking, though I don't necessarily want to encourage using eye tracking for, say, gun aiming as it would be physically exhausting for players. Object picking via eye tracking is beyond the scope of this issue, however.

**Comment by JeroMiya** [comment]
Added a tracker for an eye-tracker 2d interface in the trackerviewer scene. I also added some code to the color manager of OSVRDemo to change the color when you blink.

**Comment by JeroMiya** [comment]
Pull request up:
https://github.com/OSVR/OSVR-Unity/pull/69

**Comment by DuFF14** [comment]
EyeTracker support was merged. Closing.
