### ISSUE TITLE
Black screen at startup for some users.

### ISSUE THREAD

**Issue by DuFF14** [OSVR/OSVR-Unity#77]
Some users are experiencing a black screen at startup when running the palace demo and other Unity executables. Doesn't seem to be a problem in every build. Trying to gather more info on what might be the cause.

**Comment by wizztjh** [comment]
i am having this problem too. i seems to have this problem when i plugin razer hydra. Can anyone provide any links, so that I can help with debugging.

**Comment by wizztjh** [comment]
Output log from unity. 

https://drive.google.com/file/d/0B2mcLmaAcnbOOWZJdG4wMjI0a0k/view?usp=sharing

**Comment by wizztjh** [comment]
```
DllNotFoundException: C:/Users/tplus1/Documents/VR programming/vrprogramming_Data/Plugins/osvrClientKit.dll
  at (wrapper managed-to-native) OSVR.ClientKit.ClientContext:osvrClientInit (string,uint)
```

DLL not found.

**Comment by wizztjh** [comment]
created a new project. same problem.

**Comment by DuFF14** [comment]
Try moving the DLLs from Plugins/x86 to Plugins. Which version of Unity are you using?

**Comment by wizztjh** [comment]
I am using 5.1.

**Comment by DuFF14** [comment]
Have you tried this in the Unity editor? And this only occurs when the Razer Hydra is plugged in?

**Comment by wizztjh** [comment]
unity editor is not working too. with a few console debug log. I will paste it in later.

**Comment by DuFF14** [comment]
@wizztjh is this still an issue for you?

**Comment by wizztjh** [comment]
my OSVR is not working at all. I can't verify this.

**Comment by DuFF14** [comment]
closing this old issue, probably a setup or hardware issue.
