### ISSUE TITLE
Application.targetFrameRate is hardcoded to 60 fps

### ISSUE THREAD

**Issue by ChristophHaag** [OSVR/OSVR-Unity#78]
https://github.com/OSVR/OSVR-Unity/blob/2ff3c4092be9acaee9ede7dd29f787dc68088ce7/OSVR-Unity/Assets/OSVRUnity/src/DisplayController.cs#L47

I know, there is already a TODO there, but since osvr has an Oculus Rift DK2 plugin, a better setting may be `-1` which will render as many fps as possible.

Right now it's a bit problematic because it is not documented in e.g. http://access.osvr.com/binary/download/misc_assets/Migrating%20Unity%20applications%20from%20Oculus%20to%20OSVR%20Feb-25-15.pdf

**Comment by DuFF14** [comment]
Going to close this issue since we're no longer hardcoded to 60fps, although it's not set at -1 either (not setting it at all).
