### ISSUE TITLE
Can't build a game with x86 and x64 libs (same name)

### ISSUE THREAD

**Issue by demonixis** [OSVR/OSVR-Unity#86]
Hi,

I can't build my game with both x86 and x64 dlls of OSVR because Unity told me that a existing DLL is already present with the same name. The workaround is easy, I just remove the x64 folder. I think it can be a good idea to rename the x64 dll to be able to build a 32 and 64 bit build of the game.

demonixis.

**Comment by rpavlik** [comment]
Are you trying to build them into the same directory? You should be able to build both a 32-bit and 64-bit version, but they only differ if you put them in different places - much core unity code is in .NET which is neither 32 nor 64 bit.  For some reason, though the binaries are separated in the source trees, the Unity build process assumes you'll build each bitness into a separate folder and thus copies the matching native DLLs into a non-distinguished directory.

**Comment by DuFF14** [comment]
@demonixis is this still an issue?

**Comment by demonixis** [comment]
No this is fixed ;)
