### ISSUE TITLE
Add osvrUnityRenderingPlugin.dll to unitypackage

### ISSUE THREAD

**Issue by DuFF14** [OSVR/OSVR-Unity#88]
The DLL generated by https://github.com/OSVR/OSVR-Unity-Rendering should be included in the distributed OSVR-Unity.unitypackage.

osvrRenderManager.dll, SDL2.dll, and glew32.dll should also be included, as they are all requirements to use RenderManager in Unity.

**Comment by DuFF14** [comment]
Add d3dcompiler_47.dll to this list (distributed with RenderManager installer).

**Comment by DuFF14** [comment]
The d3dcompiler_47.dll might be a Windows 7 only issue.
Working 64bit DLLs can currently be found in the [Palace Demo](https://github.com/OSVR/OSVR-Unity-Palace-Demo/tree/master/Assets/Plugins/x86_64).

**Comment by rpavlik** [comment]
Is this something that needs CI changes? (Do you need me to do this or can you? I think you have CI access...)

**Comment by DuFF14** [comment]
Yes, I filed a new issue for adding the Unity Rendering plugin build to CI: https://github.com/OSVR/OSVR-Unity-Rendering/issues/11

I may have access, but no experience with setting up CI builds. We may also want to visit https://github.com/OSVR/OSVR-Unity/issues/89 if that also requires a CI edit.

**Comment by RedIronLabs** [comment]
Just adding this is still an issue in the current builds.  I missed providing an OSVR demo a few weeks ago because of the missing files and running low on time to try and investigate.  Seeing the issue now with the latest Unity still.  Off topic - is there a Unity Stable branch of some sort that we should be using?

**Comment by DuFF14** [comment]
Fixed by CI changes following https://github.com/OSVR/OSVR-Unity/pull/130
