### ISSUE TITLE
Move Plugins folder inside OSVRUnity folder

### ISSUE THREAD

**Issue by DuFF14** [OSVR/OSVR-Unity#89]
To keep the entire OSVR plugin contained in one folder and avoid other 3rd party DLLs from sneaking into our Plugins folder

**Comment by rpavlik** [comment]
I don't think we can do this,I thought it was a special directory name. If this is done, we'll have to adjust CI and probably search paths accordingly.

**Comment by DuFF14** [comment]
The "Plugins" name is [special](http://docs.unity3d.com/Manual/SpecialFolders.html), but it doesn't have to be directly under Assets, and there can be multiple Plugins folders in the same project. Same with "Editor" and "Resources". I think we will need to adjust CI soon anyway to add additional dependencies for RenderManager functionality https://github.com/OSVR/OSVR-Unity/issues/88

**Comment by chase-cobb** [comment]
Is this still open? @rpavlik is correct that the plugins directory can't be nested. I verified this in a local project.

The convention is to nest libraries by project inside the plugins folders.
- Android  
-- OSVR  
- x86  
-- OSVR  
- x86_64  
-- OSVR

**Comment by DuFF14** [comment]
@chase-cobb OSVR still works for me if I nest the Plugins folder inside the OSVRUnity folder. Where are you finding that convention?

**Comment by chase-cobb** [comment]
@DuFF14 I'm totally wrong. Maybe this is one of the conventions from the early days of Unity that I never mentally escaped.  Now to figure out why my project is crashing if I move the folder.

http://docs.unity3d.com/Manual/PluginInspector.html

**Comment by chase-cobb** [comment]
This pseudo convention is still done by several places that use Unity. Probably to track external dependencies easier. :8ball:

**Comment by demonixis** [comment]
Hi,

In my projects I have a special hierarchie for folders. I have a Vendors folder with all dependencies. So I have an OSVR folder with a Plugin folder in it. All works fine because the OSVR sources, don't calls dll by an absolute path, like some plugins (ProBuilder, PSMoveUnity, etc...). So it's fine, you can move the plugin folder in the OSVR folder and all will work as expected.

I suggest you to remove unecessary files like
- .mdb
- .pdb
- add_sdk_to_registry.cmd/ps1

I can send a pull request with these changes.

**Comment by DuFF14** [comment]
@demonixis Thanks! I would be ok with merging those changes, but would like consensus that we are not breaking convention. The automated build system will have to be changed at the same time, since the DLLs in the .unitypackage are copied from Managed-OSVR. I could do that part.
Any thoughts @rpavlik @chase-cobb ?

**Comment by cobbchaseRazer** [comment]
I don't see any issues with proceeding, as long as we can demonstrate that there are no negative impacts on the Android platform. It's not all shared objects (manifests and potential jars), and we should keep path lengths in mind. I can do a quick test on Android to make sure there are no issues, but it would be great if someone else could run the same test.

It will be important to document how developers update the plugin for the first time after the merge. They may need to manually delete the old plugin folder in their project to avoid multiple inclusions.

**Comment by demonixis** [comment]
I sort all my assets like that and it works pretty well for all platforms.

**Comment by nanospork** [comment]
Just want to throw my voice in there. Seems to work fine moving all the contents of Assets/Plugins under Assets/OSVRUnity/Plugins. Would be really great to make this happen, as currently to update the plugin I have to import it into an external project before moving it into my main project for cleanliness.

**Comment by DuFF14** [comment]
sorry for the slow movement on this, I will submit a PR on this soon if nobody beats me to it.

**Comment by demonixis** [comment]
Great! Can I suggest to move text files about version, etc.. in a separate folder because it's the same files in both x86 and x64 folders. It's better to versionize only needed files.

**Comment by DuFF14** [comment]
addressed in https://github.com/OSVR/OSVR-Unity/pull/213
@demonixis I didn't address that issue specifically yet, but that can be cleaned up next. I think there are some other useless files.
