### ISSUE TITLE
VRSurfaces render twice when RenderManager is disabled

### ISSUE THREAD

**Issue by ImperialPenguin** [OSVR/OSVR-Unity#96]
I've discovered a big problem when the RenderManager is not used. In the setup when the VRSurfaces are created, the cameras are disabled if the RenderManager is active, so as not to be drawn twice. The problem is that even if the RenderManager is disabled, VREye calls surface.render during it's update, then Unity draws the cameras. This increases the load on the GPU by 50% in my project. 4ms for the main camera and 1ms each for the surfaces. I can get the performance back with no noticeable side effects by either setting them to false when they are created regardless of whether RenderManager is used or by commenting out the surface.render call in VREye and letting Unity handle it. I'm not sure what the preferred method is, but in my project the framerate drops from around 80 to around 55 without the fix. So it's pretty important.

**Comment by DuFF14** [comment]
Nice find. You're talking about setting this to false always, correct? https://github.com/OSVR/OSVR-Unity/blob/master/OSVR-Unity/Assets/OSVRUnity/src/VREye.cs#L179

The main camera should only render if the showDirectModePreview boolean is checked on DisplayController. It's the worst way to enable direct mode preview until we have that feature included in RenderManager. In the non-rendermanager path or when showDirectModePreview is false, that camera gets disabled in OnPreCull() and re-enabled at the end of the frame so it shouldn't do any rendering -- are you finding that it actually renders? Or perhaps that cost is from OnPreCull()?
https://github.com/OSVR/OSVR-Unity/blob/master/OSVR-Unity/Assets/OSVRUnity/src/VRViewer.cs#L192

**Comment by ImperialPenguin** [comment]
Yes, the line you linked to is what I set to false. I'm guessing it is better to disable the surface cameras there, and let them render in precull, correct? I wasn't sure which way is best.

I don't think the main camera is actually rendering anything. But in the Unity profiler it does show up as taking around 4ms because the surface.render happens there. The 1ms each for the Unity rendering of the surfaces is wasted. When I comment out the surface.render, it takes around 2ms, then 1ms each for the surfaces. On the TrinusVR version, the two eyes combine for about 4ms. So as long as either the surface cameras are disabled, or the surface.render is disabled, OSVR takes the same amount of time as Trinus does. 

Right now, the surface cameras don't get the image effects transferred over. So I am a bit concerned that OSVR with no image effects isn't faster than Trinus with all of the image effects. So there may still be some performance issues. I'll have to get the image effects transferred over to the cameras to see.

**Comment by DuFF14** [comment]
Thanks, I opened a PR and will merge the fix tonight, unless you'd like to contribute the fix yourself since you found the bug. https://github.com/OSVR/OSVR-Unity/pull/97

Yes, I think it's better to manually render in precull and disable them after they are created. That used to be the case as you can tell by the comment on that line. This bug would have been introduced when the RenderManager path was merged in.

Interested to hear what you find with image effects, please report back. The fact that they are not copied over is an open issue (https://github.com/OSVR/OSVR-Unity/issues/75). It's on the to-do list to figure out a generalized way to copy components to each camera.

**Comment by ImperialPenguin** [comment]
You can go ahead and merge your commit. I did just fork the branch in case I get more complicated work done on it, but I don't even have Git setup on my Windows computer yet and more poor old Mac just isn't up to the task of working with VR. I'll need to figure a way to copy the image effects over, so maybe I'll have something suitable for that soon. I'd rather familiarize myself with the coding style and whatnot before doing too much. Right now I'm trying to write a script to set separate culling masks for the left and right eyes for things like rendering 3d movies, but it looks like I can't assume there will be only two eyes so figuring out a way to do that in a universal way will take a bit longer. I also have a problem with the tracker jumping to whatever orientation the headset thinks it is in instead of assuming the position on startup is the zero position like Trinus does, which makes it really hard for me to place a player in a seat. Is there a way around that, or do I need to look into that too? I've seen a few people ask about in on the forum, but they weren't answered.

**Comment by DuFF14** [comment]
A branch that works for two eyes would still be helpful towards creating a generalized solution.

For zeroing, see if this function does what you expect, and if not, open a new issue on how you think it should work:
```c#
_clientKit.context.SetRoomRotationUsingHead()
```

To reset what just happened by calling SetRoomRotationUsingHead(), try:
```c#
_clientKit.context.ClearRoomToWorldTransform()
```

**Comment by DuFF14** [comment]
One potential solution for the Image Effects is https://github.com/OSVR/OSVR-Unity/pull/99
Can continue discussion there. Closing this issue.
